spring:
    datasource:
        url: jdbc:mysql://localhost:3306/demo_project?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
        username: guest
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    main:
        allow-circular-references: true

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: false
                format_sql: true
                default_batch_fetch_size: 100
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

